### ISSUE TITLE
Thanks a lot for this library!

### ISSUE THREAD

**Issue by apahl** [markspanbroek/questionable#1]
Hi Mark,

I just wanted to let you know that I really like this library.
Elegant support for optional types is something that I am missing in Nim and this project is a big step in that direction. 

Thanks a lot.

P.S.: Thanks also for `lazy-seq`, another great library!

Kind regards,  
Axel

**Comment by markspanbroek** [comment]
Hi Axel, thanks for the kind words, I really appreciate that!
